## **Aula 10 - ML e Bioinformática**

In [49]:
!pip install biopython bioservices pandas numpy scikit-learn

In [50]:
from bioservices.uniprot import UniProt
from Bio import SeqIO
from Bio.SeqUtils.ProtParam import ProteinAnalysis
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
import pandas as pd
import io

In [51]:
uniprot = UniProt()

membrane_proteins = uniprot.search('locations:(location:"Membrane [SL-0162]") taxonomy:"Bacteria [2]"', frmt='txt', limit=1000)
cytoplasm_proteins = uniprot.search('locations:(location:"Cytoplasm [SL-0086]") taxonomy:"Bacteria [2]"', frmt='txt', limit=1000)

membrane_proteins_buffer = io.StringIO()
cytoplasm_proteins_buffer = io.StringIO()

membrane_proteins_buffer.write(membrane_proteins)
cytoplasm_proteins_buffer.write(cytoplasm_proteins)

membrane_proteins_buffer.seek(0)
cytoplasm_proteins_buffer.seek(0)

0

In [52]:
membrane_proteins_parser = SeqIO.parse(membrane_proteins_buffer,'swiss')
cytoplasm_proteins_parser = SeqIO.parse(cytoplasm_proteins_buffer,'swiss')

df_membrane_proteins = pd.DataFrame()
df_cytoplasm_proteins = pd.DataFrame()

for record in membrane_proteins_parser:
  protein_analysis = ProteinAnalysis(str(record.seq))
  aminoacid_composition = protein_analysis.get_amino_acids_percent()
  df_membrane_proteins = df_membrane_proteins.append([aminoacid_composition], ignore_index=True)

for record in cytoplasm_proteins_parser:
  protein_analysis = ProteinAnalysis(str(record.seq))
  aminoacid_composition = protein_analysis.get_amino_acids_percent()
  df_cytoplasm_proteins = df_cytoplasm_proteins.append([aminoacid_composition], ignore_index=True)

In [53]:
df_cytoplasm_proteins[['A', 'C']]

A         C
0    0.072727  0.000000
1    0.034783  0.008696
2    0.049242  0.018939
3    0.098039  0.013072
4    0.094862  0.019763
..        ...       ...
995  0.113074  0.007067
996  0.113074  0.007067
997  0.113074  0.007067
998  0.184466  0.008091
999  0.165049  0.006472

[1000 rows x 2 columns]

In [54]:
df_cytoplasm_proteins.drop(['A'], axis=1)

C         D         E  ...         V         W         Y
0    0.000000  0.069697  0.124242  ...  0.060606  0.009091  0.021212
1    0.008696  0.052174  0.086957  ...  0.043478  0.000000  0.052174
2    0.018939  0.079545  0.049242  ...  0.049242  0.026515  0.034091
3    0.013072  0.078431  0.065359  ...  0.071895  0.006536  0.052288
4    0.019763  0.083004  0.023715  ...  0.090909  0.011858  0.019763
..        ...       ...       ...  ...       ...       ...       ...
995  0.007067  0.067138  0.053004  ...  0.045936  0.010601  0.042403
996  0.007067  0.067138  0.053004  ...  0.045936  0.010601  0.042403
997  0.007067  0.067138  0.053004  ...  0.045936  0.010601  0.042403
998  0.008091  0.071197  0.035599  ...  0.103560  0.011327  0.012945
999  0.006472  0.056634  0.053398  ...  0.118123  0.008091  0.008091

[1000 rows x 19 columns]

In [55]:
df_cytoplasm_proteins.drop([1], axis=0)

A         C         D  ...         V         W         Y
0    0.072727  0.000000  0.069697  ...  0.060606  0.009091  0.021212
2    0.049242  0.018939  0.079545  ...  0.049242  0.026515  0.034091
3    0.098039  0.013072  0.078431  ...  0.071895  0.006536  0.052288
4    0.094862  0.019763  0.083004  ...  0.090909  0.011858  0.019763
5    0.072340  0.014894  0.057447  ...  0.071277  0.003191  0.026596
..        ...       ...       ...  ...       ...       ...       ...
995  0.113074  0.007067  0.067138  ...  0.045936  0.010601  0.042403
996  0.113074  0.007067  0.067138  ...  0.045936  0.010601  0.042403
997  0.113074  0.007067  0.067138  ...  0.045936  0.010601  0.042403
998  0.184466  0.008091  0.071197  ...  0.103560  0.011327  0.012945
999  0.165049  0.006472  0.056634  ...  0.118123  0.008091  0.008091

[999 rows x 20 columns]

In [56]:
df_cytoplasm_proteins

A         C         D  ...         V         W         Y
0    0.072727  0.000000  0.069697  ...  0.060606  0.009091  0.021212
1    0.034783  0.008696  0.052174  ...  0.043478  0.000000  0.052174
2    0.049242  0.018939  0.079545  ...  0.049242  0.026515  0.034091
3    0.098039  0.013072  0.078431  ...  0.071895  0.006536  0.052288
4    0.094862  0.019763  0.083004  ...  0.090909  0.011858  0.019763
..        ...       ...       ...  ...       ...       ...       ...
995  0.113074  0.007067  0.067138  ...  0.045936  0.010601  0.042403
996  0.113074  0.007067  0.067138  ...  0.045936  0.010601  0.042403
997  0.113074  0.007067  0.067138  ...  0.045936  0.010601  0.042403
998  0.184466  0.008091  0.071197  ...  0.103560  0.011327  0.012945
999  0.165049  0.006472  0.056634  ...  0.118123  0.008091  0.008091

[1000 rows x 20 columns]

In [57]:
df_membrane_proteins

A         C         D  ...         V         W         Y
0    0.118357  0.019324  0.026570  ...  0.101449  0.012077  0.012077
1    0.094982  0.000000  0.055556  ...  0.062724  0.001792  0.010753
2    0.120419  0.020942  0.073298  ...  0.089005  0.020942  0.010471
3    0.104895  0.009324  0.023310  ...  0.100233  0.009324  0.020979
4    0.101124  0.000000  0.112360  ...  0.044944  0.011236  0.000000
..        ...       ...       ...  ...       ...       ...       ...
995  0.078801  0.006659  0.058824  ...  0.056604  0.007769  0.028857
996  0.058608  0.000000  0.062271  ...  0.073260  0.009158  0.027473
997  0.094077  0.006969  0.059233  ...  0.087108  0.006969  0.038328
998  0.070707  0.010101  0.020202  ...  0.131313  0.005051  0.030303
999  0.122302  0.000000  0.043165  ...  0.071942  0.000000  0.028777

[1000 rows x 20 columns]

In [58]:
df_membrane_proteins['membrane'] = True
df_cytoplasm_proteins['membrane'] = False

In [59]:
df = pd.concat([df_membrane_proteins, df_cytoplasm_proteins])

In [60]:
df

A         C         D  ...         W         Y  membrane
0    0.118357  0.019324  0.026570  ...  0.012077  0.012077      True
1    0.094982  0.000000  0.055556  ...  0.001792  0.010753      True
2    0.120419  0.020942  0.073298  ...  0.020942  0.010471      True
3    0.104895  0.009324  0.023310  ...  0.009324  0.020979      True
4    0.101124  0.000000  0.112360  ...  0.011236  0.000000      True
..        ...       ...       ...  ...       ...       ...       ...
995  0.113074  0.007067  0.067138  ...  0.010601  0.042403     False
996  0.113074  0.007067  0.067138  ...  0.010601  0.042403     False
997  0.113074  0.007067  0.067138  ...  0.010601  0.042403     False
998  0.184466  0.008091  0.071197  ...  0.011327  0.012945     False
999  0.165049  0.006472  0.056634  ...  0.008091  0.008091     False

[2000 rows x 21 columns]

In [61]:
X = df.drop(['membrane'], axis=1)
y = df['membrane']

In [62]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [63]:
X_train

A         C         D  ...         V         W         Y
92   0.146853  0.006993  0.055944  ...  0.090909  0.000000  0.013986
897  0.194030  0.000000  0.029851  ...  0.089552  0.044776  0.014925
893  0.088692  0.004435  0.031042  ...  0.066519  0.037694  0.026608
730  0.087209  0.000000  0.058140  ...  0.069767  0.017442  0.040698
402  0.072202  0.025271  0.046931  ...  0.097473  0.010830  0.014440
..        ...       ...       ...  ...       ...       ...       ...
708  0.093750  0.031250  0.000000  ...  0.031250  0.000000  0.031250
398  0.107200  0.000000  0.080000  ...  0.091200  0.004800  0.012800
325  0.081818  0.027273  0.009091  ...  0.045455  0.036364  0.045455
511  0.113074  0.007067  0.070671  ...  0.045936  0.010601  0.042403
625  0.090323  0.025806  0.051613  ...  0.064516  0.006452  0.032258

[1500 rows x 20 columns]

In [64]:
X_test

A         C         D  ...         V         W         Y
744  0.113074  0.007067  0.070671  ...  0.045936  0.010601  0.042403
343  0.082251  0.010101  0.057720  ...  0.063492  0.007215  0.030303
26   0.119850  0.003745  0.067416  ...  0.074906  0.007491  0.029963
709  0.093640  0.026502  0.054770  ...  0.068905  0.014134  0.028269
357  0.103529  0.002353  0.032941  ...  0.077647  0.014118  0.035294
..        ...       ...       ...  ...       ...       ...       ...
584  0.102837  0.010638  0.024823  ...  0.060284  0.056738  0.042553
817  0.075075  0.003003  0.066066  ...  0.084084  0.018018  0.042042
811  0.113074  0.007067  0.067138  ...  0.049470  0.010601  0.042403
317  0.111455  0.004644  0.074303  ...  0.035604  0.020124  0.044892
41   0.169231  0.000000  0.069231  ...  0.038462  0.000000  0.015385

[500 rows x 20 columns]

In [65]:
model = SVC()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

print(accuracy)

0.83


In [66]:
def predict_membrane_proteins(protein_sequence):
  protein_analysis = ProteinAnalysis(protein_sequence)
  aminoacid_composition = protein_analysis.get_amino_acids_percent()
  df = pd.DataFrame([aminoacid_composition])
  result = model.predict(df)
  return result

In [67]:
sequence = '''
MSQNTLKVHDLNEDAEFDENGVEVFDEKALVEQEPSDNDLAEEELLSQGATQRVLDATQL
YLGEIGYSPLLTAEEEVYFARRALRGDVASRRRMIESNLRLVVKIARRYGNRGLALLDLI
EEGNLGLIRAVEKFDPERGFRFSTYATWWIRQTIERAIMNQTRTIRLPIHIVKELNVYLR
TARELSHKLDHEPSAEEIAEQLDKPVDDVSRMLRLNERITSVDTPLGGDSEKALLDILAD
EKENGPEDTTQDDDMKQSIVKWLFELNAKQREVLARRFGLLGYEAATLEDVGREIGLTRE
RVRQIQVEGLRRLREILQTQGLNIEALFRE
'''

predict_membrane_proteins(sequence)

array([False])

In [68]:
sequence = '''
MKKLLPILIGLSLSGFSSLSQAENLMQVYQQARLSNPELRKSAADRDAAFEKINEARSPL
LPQLGLGADYTYSNGYRDANGINSNATSASLQLTQSIFDMSKWRALTLQEKAAGIQDVTY
QTDQQTLILNTATAYFNVLNAIDVLSYTQAQKEAIYRQLDQTTQRFNVGLVAITDVQNAR
AQYDTVLANEVTARNNLDNAVEQLRQITGNYYPELAALNVENFKTDKPQPVNALLKEAEK
RNLSLLQARLSQDLAREQIRQAQDGHLPTLDLTASTGISDTSYSGSKTRGAAGTQYDDSN
MGQNKVGLSFSLPIYQGGMVNSQVKQAQYNFVGASEQLESAHRSVVQTVRSSFNNINASI
SSINAYKQAVVSAQSSLDAMEAGYSVGTRTIVDVLDATTTLYNAKQELANARYNYLINQL
NIKSALGTLNEQDLLALNNALSKPVSTNPENVAPQTPEQNAIADGYAPDSPAPVVQQTSA
RTTTSNGHNPFRN
'''

predict_membrane_proteins(sequence)

array([ True])

## **Atividade Aula 10**

In [69]:
sequence = '''
MEKTYNPQDIEQPLYEHWEKQGYFKPNGDESQESFCIMIPPPNVTGSLHMGHAFQQTIMD
TMIRYQRMQGKNTLWQVGTDHAGIATQMVVERKIAAEEGKTRHDYGREAFIDKIWEWKAE
SGGTITRQMRRLGNSVDWERERFTMDEGLSNAVKEVFVRLYKEDLIYRGKRLVNWDPKLR
TAISDLEVENRESKGSMWHIRYPLADGAKTADGKDYLVVATTRPETLLGDTGVAVNPEDP
RYKDLIGKYVILPLVNRRIPIVGDEHADMEKGTGCVKITPAHDFNDYEVGKRHALPMINI
LTFDGDIRESAQVFDTKGNESDVYSSEIPAEFQKLERFAARKAVVAAVDALGLLEEIKPH
DLTVPYGDRGGVVIEPMLTDQWYVRADVLAKPAVEAVENGDIQFVPKQYENMYFSWMRDI
QDWCISRQLWWGHRIPAWYDEAGNVYVGRNEDEVRKENNLGADVVLRQDEDVLDTWFSSA
LWTFSTLGWPENTDALRQFHPTSVMVSGFDIIFFWIARMIMMTMHFIKDENGKPQVPFHT
VYMTGLIRDDEGQKMSKSKGNVIDPLDMVDGISLPELLEKRTGNMMQPQLADKIRKRTEK
QFPNGIEPHGTDALRFTLAALASTGRDINWDMKRLEGYRNFCNKLWNASRFVLMNTEGQD
CGFNGGEMTLSLADRWILAEFNQTIKAYREALDSFRFDIAAGILYEFTWNQFCDWYLELT
KPVMNGGTEAELRGTRHTLVTVLEGLLRLAHPIIPFITETIWQRVKVLCGITADTIMLQP
FPQYDASQVDEAALADTEWLKQAIVAVRNIRAEMNIAPGKPLELLLRGCSADAERRVNEN
RGFLQTLARLESITVLPADDKGPVSVTKIIDGAELLIPMAGLINKEDELARLAKEVAKIE
GEISRIENKLANEGFVARAPEAVIAKEREKLEGYAEAKAKLIEQQAVIAAL
'''
predict_membrane_proteins(sequence)

array([False])

In [70]:
sequence = '''
MPKPADHRNHAAVSTSVLSALFLGAGAALLSACSSPQHASTVPGTTPSIWTGSPAPSGLS
GHDEESPGAQSLTSTLTAPDGTKVATAKFEFANGYATVTIATTGVGKLTPGFHGLHIHQV
GKCEPNSVAPTGGAPGNFLSAGGHYHVPGHTGTPASGDLASLQVRGDGSAMLVTTTDAFT
MDDLLSGAKTAIIIHAGADNFANIPPERYVQVNGTPGPDETTLTTGDAGKRVACGVIGSG
'''
predict_membrane_proteins(sequence)

array([ True])

In [71]:
sequence = '''
MDKIEVRGARTHNLKNINLVIPRDKLIVVTGLSGSGKSSLAFDTLYAEGQRRYVESLSAY
ARQFLSLMEKPDVDHIEGLSPAISIEQKSTSHNPRSTVGTITEIHDYLRLLFARVGEPRC
PDHDVPLAAQTVSQMVDNVLSQPEGKRLMLLAPIIKERKGEHTKTLENLASQGYIRARID
GEVCDLSDPPKLELQKKHTIEVVVDRFKVRDDLTQRLAESFETALELSGGTAVVADMDDP
KAEELLFSANFACPICGYSMRELEPRLFSFNNPAGACPTCDGLGVQQYFDPDRVIQNPEL
SLAGGAIRGWDRRNFYYFQMLKSLADHYKFDVEAPWGSLSANVHKVVLYGSGKENIEFKY
MNDRGDTSIRRHPFEGVLHNMERRYKETESSAVREELAKFISNRPCASCEGTRLRREARH
VYVENTPLPAISDMSIGHAMEFFNNLKLAGQRAKIAEKILKEIGDRLKFLVNVGLNYLTL
SRSAETLSGGEAQRIRLASQIGAGLVGVMYVLDEPSIGLHQRDNERLLGTLIHLRDLGNT
VIVVEHDEDAIRAADHVIDIGPGAGVHGGEVVAEGPLEAIMAVPESLTGQYMSGKRKIEV
PKKRVPANPEKVLKLTGARGNNLKDVTLTLPVGLFTCITGVSGSGKSTLINDTLFPIAQR
QLNGATIAEPAPYRDIQGLEHFDKVIDIDQSPIGRTPRSNPATYTGVFTPVRELFAGVPE
SRARGYTPGRFSFNVRGGRCEACQGDGVIKVEMHFLPDIYVPCDQCKGKRYNRETLEIKY
KGKTIHEVLDMTIEEAREFFDAVPALARKLQTLMDVGLTYIRLGQSATTLSGGEAQRVKL
ARELSKRGTGQTLYILDEPTTGLHFADIQQLLDVLHKLRDQGNTIVVIEHNLDVIKTADW
IVDLGPEGGSGGGEILVSGTPETVAECEASHTARFLKPML
'''

predict_membrane_proteins(sequence)

array([False])